INSERT INTO States (state_id, name, abbreviation, region_id) 
VALUES
    (1, 'Alabama', 'AL', 3),
    (2, 'Alaska', 'AK', 4),
    (3, 'Arizona', 'AZ', 4),
    (4, 'Arkansas', 'AR', 3),
    (5, 'California', 'CA', 4),
    (6, 'Colorado', 'CO', 4),
    (7, 'Connecticut', 'CT', 1),
    (8, 'Delaware', 'DE', 1),
    (9, 'Florida', 'FL', 3),
    (10, 'Georgia', 'GA', 3),
    (11, 'Hawaii', 'HI', 4),
    (12, 'Idaho', 'ID', 4),
    (13, 'Illinois', 'IL', 2),
    (14, 'Indiana', 'IN', 2),
    (15, 'Iowa', 'IA', 2),
    (16, 'Kansas', 'KS', 2),
    (17, 'Kentucky', 'KY', 3),
    (18, 'Louisiana', 'LA', 3),
    (19, 'Maine', 'ME', 1),
    (20, 'Maryland', 'MD', 1),
    (21, 'Massachusetts', 'MA', 1),
    (22, 'Michigan', 'MI', 2),
    (23, 'Minnesota', 'MN', 2),
    (24, 'Mississippi', 'MS', 3),
    (25, 'Missouri', 'MO', 2),
    (26, 'Montana', 'MT', 4),
    (27, 'Nebraska', 'NE', 2),
    (28, 'Nevada', 'NV', 4),
    (29, 'New Hampshire', 'NH', 1),
    (30, 'New Jersey', 'NJ', 1),
    (31, 'New Mexico', 'NM', 4),
    (32, 'New York', 'NY', 1),
    (33, 'North Carolina', 'NC', 3),
    (34, 'North Dakota', 'ND', 2),
    (35, 'Ohio', 'OH', 2),
    (36, 'Oklahoma', 'OK', 3),
    (37, 'Oregon', 'OR', 4),
    (38, 'Pennsylvania', 'PA', 1),
    (39, 'Rhode Island', 'RI', 1),
    (40, 'South Carolina', 'SC', 3),
    (41, 'South Dakota', 'SD', 2),
    (42, 'Tennessee', 'TN', 3),
    (43, 'Texas', 'TX', 3),
    (44, 'Utah', 'UT', 4),
    (45, 'Vermont', 'VT', 1),
    (46, 'Virginia', 'VA', 3),
    (47, 'Washington', 'WA', 4),
    (48, 'West Virginia', 'WV', 3),
    (49, 'Wisconsin', 'WI', 2),
    (50, 'Wyoming', 'WY', 4),
    (51, 'District of Columbia', 'DC', 1);
